{{- $name := include "bacchus-gpu.fullname" . }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ $name }}-selfsigned
spec:
  selfSigned: {}
---

apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ $name }}-issuer
spec:
  ca:
    secretName: {{ $name }}-ca-cert
---

# root ca cert (self-signed, long expiration)
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ $name }}-ca
spec:
  secretName: {{ $name }}-ca-cert
  commonName: {{ $name }}-ca
  isCA: true
  duration: 876000h # 100y
  renewBefore: 360h # 15d
  issuerRef:
    name: {{ $name }}-selfsigned
    kind: Issuer
---

# cert for admission webhook (signed by our root ca)
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ $name }}
spec:
  secretName: {{ $name }}-cert
  commonName: {{ printf "%s-admission" $name }}
  dnsNames:
  - {{ printf "%s-admission.%s" $name .Release.Namespace }}
  - {{ printf "%s-admission.%s.svc" $name .Release.Namespace }}
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  issuerRef:
    name: {{ $name }}-issuer
    kind: Issuer
---
