{{- $name := include "bacchus-gpu.fullname" . }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}-admission
  labels:
    {{- include "bacchus-gpu.labels" . | nindent 4 }}
spec:
  type: {{ .Values.admission.service.type }}
  ports:
    - port: {{ .Values.admission.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "bacchus-gpu.selectorLabels" . | nindent 4 }}
---
