controller:
  replicaCount: 1
  image:
    repository: "ghcr.io/bacchus-snu/bacchus-gpu-controller"
    pullPolicy: Always
    tag: "latest"

  imagePullSecrets: []
  nameOverride: ""
  fullnameOverride: ""

  serviceAccount:
    annotations: {}

  podAnnotations: {}

  podSecurityContext: {}

  securityContext: {}

  service:
    type: ClusterIP
    port: 12322

  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}

  livenessProbe:
    httpGet:
      path: /health
      port: http
  readinessProbe:
    httpGet:
      path: /health
      port: http

  configs:
    rust_log: "info"

admission:
  replicaCount: 2
  image:
    repository: "ghcr.io/bacchus-snu/bacchus-gpu-controller"
    pullPolicy: Always
    tag: "latest"

  imagePullSecrets: []
  nameOverride: ""
  fullnameOverride: ""

  serviceAccount:
    annotations: {}

  podAnnotations: {}

  podSecurityContext: {}

  securityContext: {}

  service:
    type: ClusterIP
    port: 12321

  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}

  livenessProbe:
    httpGet:
      path: /health
      port: http
      scheme: HTTPS
  readinessProbe:
    httpGet:
      path: /health
      port: http
      scheme: HTTPS

  configs:
    rust_log: "info"
    oidc_username_prefix: "oidc:"
    default_role_name: "edit"
    # comma-separated group list
    authorized_group_names: "gpu,admin"
