controller:
  replicaCount: 1
  image:
    repository: "ghcr.io/skystar-p/bacchus-gpu-controller"
    pullPolicy: Always
    tag: "latest"

  imagePullSecrets: []
  nameOverride: ""
  fullnameOverride: ""

  serviceAccount:
    annotations: {}

  podAnnotations: {}

  podSecurityContext: {}

  securityContext: {}

  service:
    type: ClusterIP
    port: 12321

  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}

  livenessProbe:
    httpGet:
      path: /health
      port: http
  readinessProbe:
    httpGet:
      path: /health
      port: http

admission:
  replicaCount: 2
  image:
    repository: "ghcr.io/skystar-p/bacchus-gpu-controller"
    pullPolicy: Always
    tag: "latest"

  imagePullSecrets: []
  nameOverride: ""
  fullnameOverride: ""

  serviceAccount:
    annotations: {}

  podAnnotations: {}

  podSecurityContext: {}

  securityContext: {}

  service:
    type: ClusterIP
    port: 12321

  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}

  livenessProbe:
    httpGet:
      path: /health
      port: http
  readinessProbe:
    httpGet:
      path: /health
      port: http
