{{- $name := include "bacchus-gpu.fullname" . }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ $name }}-userbootstraps-default-role
rules:
  - apiGroups:
      - bacchus.io
    resources:
      - userbootstraps
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ $name }}-userbootstraps-default-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ $name }}-userbootstraps-default-role
subjects:
{{- range .Values.admission.configs.authorized_group_names }}
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: {{ . }}
{{- end }}
---
