{{- $name := include "bacchus-gpu.fullname" . }}
{{- $component := "controller" }}
{{- $ctx := get .Values $component }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $name }}-{{ $component }}
  labels:
    {{- include "bacchus-gpu.labels" . | nindent 4 }}
spec:
  replicas: {{ $ctx.replicaCount }}
  selector:
    matchLabels:
      {{- include "bacchus-gpu.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with $ctx.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "bacchus-gpu.selectorLabels" . | nindent 8 }}
    spec:
      {{- with $ctx.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ $name }}-{{ $component }}
      securityContext:
        {{- toYaml $ctx.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ $component }}
          securityContext:
            {{- toYaml $ctx.securityContext | nindent 12 }}
          image: "{{ $ctx.image.repository }}:{{ $ctx.image.tag | default $.Chart.AppVersion }}"
          imagePullPolicy: {{ $ctx.image.pullPolicy }}
          command:
            - {{ printf "/app/%s" $component | quote }}
          env:
            - name: RUST_LOG
              value: {{ $ctx.configs.rust_log | quote }}
            - name: CONF_LISTEN_ADDR
              value: "0.0.0.0"
            - name: CONF_LISTEN_PORT
              value: {{ $ctx.service.port | quote }}
          ports:
            - name: http
              containerPort: {{ $ctx.service.port }}
              protocol: TCP
          {{- with $ctx.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $ctx.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml $ctx.resources | nindent 12 }}
      {{- with $ctx.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $ctx.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $ctx.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---

{{- $component := "admission" }}
{{- $ctx := get .Values $component }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $name }}-{{ $component }}
  labels:
    {{- include "bacchus-gpu.labels" . | nindent 4 }}
spec:
  replicas: {{ $ctx.replicaCount }}
  selector:
    matchLabels:
      {{- include "bacchus-gpu.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with $ctx.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "bacchus-gpu.selectorLabels" . | nindent 8 }}
    spec:
      {{- with $ctx.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ $name }}-{{ $component }}
      securityContext:
        {{- toYaml $ctx.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ $component }}
          securityContext:
            {{- toYaml $ctx.securityContext | nindent 12 }}
          image: "{{ $ctx.image.repository }}:{{ $ctx.image.tag | default $.Chart.AppVersion }}"
          imagePullPolicy: {{ $ctx.image.pullPolicy }}
          command:
            - {{ printf "/app/%s" $component | quote }}
          env:
            - name: RUST_LOG
              value: {{ $ctx.configs.rust_log | quote }}
            - name: CONF_LISTEN_ADDR
              value: "0.0.0.0"
            - name: CONF_LISTEN_PORT
              value: {{ $ctx.service.port | quote }}
            - name: CONF_CERT_PATH
              value: "/cert/tls.crt"
            - name: CONF_KEY_PATH
              value: "/cert/tls.key"
            - name: CONF_OIDC_USERNAME_PREFIX
              value: {{ $ctx.configs.oidc_username_prefix | quote }}
            - name: CONF_DEFAULT_ROLE_NAME
              value: {{ $ctx.configs.default_role_name | quote }}
            - name: CONF_AUTHORIZED_GROUP_NAMES
              value: "{{- include "bacchus-gpu.authorizedGroupNamesWithCommas" . }}"
          volumeMounts:
            - name: cert
              mountPath: /cert
              readOnly: true
          ports:
            - name: http
              containerPort: {{ $ctx.service.port }}
              protocol: TCP
          {{- with $ctx.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $ctx.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml $ctx.resources | nindent 12 }}
      volumes:
        - name: cert
          secret:
            secretName: {{ $name }}-cert
      {{- with $ctx.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $ctx.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $ctx.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---

{{- $component := "synchronizer" }}
{{- $ctx := get .Values $component }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $name }}-{{ $component }}
  labels:
    {{- include "bacchus-gpu.labels" . | nindent 4 }}
spec:
  replicas: {{ $ctx.replicaCount }}
  selector:
    matchLabels:
      {{- include "bacchus-gpu.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with $ctx.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "bacchus-gpu.selectorLabels" . | nindent 8 }}
    spec:
      {{- with $ctx.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ $name }}-{{ $component }}
      securityContext:
        {{- toYaml $ctx.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ $component }}
          securityContext:
            {{- toYaml $ctx.securityContext | nindent 12 }}
          image: "{{ $ctx.image.repository }}:{{ $ctx.image.tag | default $.Chart.AppVersion }}"
          imagePullPolicy: {{ $ctx.image.pullPolicy }}
          command:
            - {{ printf "/app/%s" $component | quote }}
          env:
            - name: RUST_LOG
              value: {{ $ctx.configs.rust_log | quote }}
            - name: CONF_LISTEN_ADDR
              value: "0.0.0.0"
            - name: CONF_LISTEN_PORT
              value: {{ $ctx.service.port | quote }}
            - name: CONF_GOOGLE_SERVICE_ACCOUNT_JSON_PATH
              value: "/google_service_account_json/key.json"
            - name: CONF_GOOGLE_FILE_ID
              value: {{ $ctx.configs.google_file_id | quote }}
            - name: CONF_SYNC_INTERVAL_SECS
              value: {{ $ctx.configs.sync_interval_secs | quote }}
            - name: CONF_GPU_SERVER_NAME
              value: {{ $ctx.configs.gpu_server_name | quote }}
          volumeMounts:
            - name: google_service_account_json
              mountPath: /google_service_account_json
              readOnly: true
          ports:
            - name: http
              containerPort: {{ $ctx.service.port }}
              protocol: TCP
          {{- with $ctx.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $ctx.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml $ctx.resources | nindent 12 }}
      volumes:
        - name: google_service_account_json
          secret:
            secretName: {{ $ctx.configs.google_service_account_json_secret_name }}
      {{- with $ctx.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $ctx.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $ctx.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
